name: shared_str
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  #imported packages
  auth_blocks:
    hosted: https://dart.pkg.jetbrains.space/akarinti/p/main/dart/
    version: ^0.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ">=2.3.0 <2.3.2"
  intl_utils: 
    git: 
      url: https://github.com/nridwan/intl_utils.git
      ref: feat/modular_and_overridables

flutter_intl:
  main_locale: en_US
  enabled: true
  class_name: SharedStr
  implements: AuthStr
  imports: 
    - "'package:auth_blocks/auth_blocks.dart'"
  sync:
    auth_blocks:
