name: ait_flutter_template
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.0
  #LocalDeps
  common_dependency: ^0.0.1
  dependency_injection: ^0.0.1
  auth: ^0.0.1
  navigation: ^0.0.1
  env: ^0.0.1
  #RemoteDeps
  ait_design_generator_annotation:
    hosted: https://dart.pkg.jetbrains.space/akarinti/p/main/dart/
    version: ^0.0.1
  # freezed_annotation: ^2.2.0
  go_router: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ">=2.3.0 <2.3.2"
  ait_design_generator:
    hosted: https://dart.pkg.jetbrains.space/akarinti/p/main/dart/
    version: ^0.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Black.ttf
        - asset: fonts/Satoshi-BlackItalic.ttf
          style: italic
        - asset: fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: fonts/Satoshi-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Satoshi-Italic.ttf
          style: italic
        - asset: fonts/Satoshi-Light.ttf
          weight: 200
        - asset: fonts/Satoshi-LightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Satoshi-Medium.ttf
          weight: 600
        - asset: fonts/Satoshi-MediumItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: fonts/Satoshi-Variable.ttf
        - asset: fonts/Satoshi-VariableItalic.ttf
