name: navigation
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Local Deps
  auth: ^0.0.1
  splash_feature: ^0.0.1
  nav_list: ^0.0.1
  otp: ^0.0.1
  # Remote Deps
  go_router: ^6.0.6
  auth_blocks:
    hosted: https://dart.pkg.jetbrains.space/akarinti/p/main/dart/
    version: ^0.0.3
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
